usersJsonFile:  "./users.json"
ticketsJsonFile: "./tickets.json"
organizationsJsonFile: "./organizations.json"
outputfields:
  users:
     - "_id"
     - "url"
     - "external_id"
     - "name"
     - "alias"
     - "created_at"
     - "active"
     - "verified"
     - "shared"
     - "locale"
     - "timezone"
     - "last_login_at"
     - "email"
     - "phone"
     - "signature"
     - "organization_id"
     - "tags"
     - "suspended"
     - "role"
  tickets:
     - "_id"
     - "url"
     - "external_id"
     - "created_at"
     - "type"
     - "subject"
     - "description"
     - "priority"
     - "status"
     - "submitter_id"
     - "assignee_id"
     - "organization_id"
     - "tags"
     - "has_incidents"
     - "due_at"
     - "via"
  organizations:
     - "_id"
     - "url"
     - "external_id"
     - "name"
     - "domain_names"
     - "created_at"
     - "details"
     - "shared_tickets"
     - "tags"
relatedoutputfields:
  users:
     - "name"
     - "alias"
     - "active"
     - "verified"
     - "shared"
     - "timezone"
     - "suspended"
     - "role"
  tickets:
     - "created_at"
     - "type"
     - "subject"
     - "description"
     - "priority"
     - "status"
     - "has_incidents"
     - "due_at"
     - "via"
  organizations:
     - "name"
     - "domain_names"
     - "details"
     - "shared_tickets"