usersJsonFile:  "./users.json"
ticketsJsonFile: "./tickets.json"
organizationsJsonFile: "./organizations.json"
outputfields:
  users:
     - "_id"
     - "name"
     - "timezone"
  tickets:
     - "_id"
     - "subject"
     - "type"
  organizations:
     -  "_id"
     -  "name"
     - "domain_names"
     - "tags"
relatedoutputfields:
  users:
     - "_id"
     - "name"
     - "timezone"
  tickets:
     - "_id"
     - "subject"
     - "type"
  organizations:
     -  "_id"
     -  "name"
     - "domain_names"
     - "tags"